### ISSUE TITLE
Plans to move caching into the cloud

### ISSUE THREAD

**Issue by non-Jedi** [julia-vscode/SymbolServer.jl#162] opened 2020-06-01 17:57 UTC
@davidanthoff I saw you mention in #160 and #161 that you plan to move caching into the cloud. Could you expand a little bit on the proposed architecture for doing so? Culturally I think that several of the downstream clients for LanguageServer.jl other than vscode will tend to be more uncomfortable with such a change. Specifically I'd like to know if the thought is that:

- Caching of symbols on user's machines continues to be the default for LanguageServer.jl, but vscode will provide a mechanism to download caches
- Caching of symbols on user's machines continues to be the default for LanguageServer.jl, but an option can be passed to `LanguageServerInstance` to download caches.
- LanguageServer.jl will default to downloading caches
- Something else I haven't considered

**Comment by ZacLN** [comment] 2020-06-01 18:17
Somewhere in region of the first two I'd say.

**Comment by davidanthoff** [comment] 2020-06-01 18:26
Yes, this will definitely be optional! The way I think about this right now is that currently we have one way to create these cache files (local indexing), going forward we'll have to (download from cloud and local indexing). Even for VS Code we will want to continue to have the local indexing option, for example when a user is offline I imagine that the LS would first try to download the cache file from the cloud, but when that doesn't work because there is no internet, it would fall back to the usual local indexing mechanism.

So we can definitely have an option that just disables the cloud download, which would essentially be equivalent to the mode for VS Code where the internet is down.

**Comment by davidanthoff** [comment] 2020-06-01 18:26
Oh, and closing this as a duplicate of https://github.com/julia-vscode/SymbolServer.jl/issues/108.

**Closed by davidanthoff** 2020-06-01 18:26 UTC
